### ISSUE TITLE
Error - No module named 'scapy.modules.six.moves'

### ISSUE THREAD

**Issue by SV-ZeroOne** [csandker/pxethiefy#5]
Good day,

I recently tried to use your tool on a fresh kali linux install.
I have previously used your tool and never had this problem. 
I followed the latest readme.md instructions you put up and I'm getting this error.
Please can you help me resolve this and can anyone else confirm if they are experincing the same issue?

_Traceback (most recent call last):
  File "/home/neo/Tools/pxethiefy/pxethiefy.py", line 9, in <module>
    from scapy.all import *
  File "/root/miniconda3/envs/pxethiefy/lib/python3.12/site-packages/scapy/all.py", line 10, in <module>
    from scapy.base_classes import *
  File "/root/miniconda3/envs/pxethiefy/lib/python3.12/site-packages/scapy/base_classes.py", line 32, in <module>
    from scapy.modules.six.moves import range
ModuleNotFoundError: No module named 'scapy.modules.six.moves'_

Many thanks.

**Comment by SV-ZeroOne** [comment]
Just some update:
Installing scappy version 2.6.0 removes the above error but results in the bellow error that I believe you tried to fix in a previously closed issue: https://github.com/csandker/pxethiefy/issues/4 

_[-] An error occured while trying to get MAC/IP from interface 'eth0'...
  Error was: name 'get_if_raw_hwaddr' is not defined_ 
  
  So there seems to be something more to this problem that we are experincing.

**Comment by 7MinSec** [comment]
Just adding a "same here."  Happened on a fresh install of Ubuntu.  I find that if I run with the `explore -i eth0 -a sometarget.domain.com` it works, but the general run gives the `Error was: name 'get_if_raw_hwaddr' is not defined` as you noted.

**Comment by csandker** [comment]
Hi @SV-ZeroOne,

haven't used Kali in a while, but just downloaded and tested with the latest version. 
Worked with the instructions from the Readme.  

![2024-10-29_09-36](https://github.com/user-attachments/assets/62ec8fde-5cd7-449b-856e-18541530e519)

But I know that the original PxeThief tool (https://github.com/MWR-CyberSec/PXEThief) recently added Linux support by removing some of the Windows-only libraries. Maybe worth to give this a shot

**Comment by phefley** [comment]
Been having issues with this as well. Using the updates from issue #4 and removing the version pinning for scapy received the following error:
```
[-] An error occured while trying to get MAC/IP from interface 'eth0'...
Error was: name 'get_if_raw_hwaddr' is not defined
```

Not a completely solid workaround, but this worked for me and might help diagnose the issue:
```python
from scapy.all import *
from scapy.arch.unix import get_if_raw_hwaddr
```

**Comment by EAGAIIN** [comment]
Using python3.11 seems to be work around

**Comment by 7MinSec** [comment]
@EAGAIIN thank you!  Ok in my lab I kind of threw the kitchen sink at a Ubuntu 22.04 box to get Python3.11 going, and while I don't think I needed ALL of this, this is what got me going:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11 -y
sudo apt install python3-virtualenv -y
virtualenv -p python3.11 venv
source venv/bin/activate

# sudo apt install -y build-essential python3.11-dev python3.11-venv python3-pip libffi-dev libssl-dev libpcap-dev - I'm not sure this actually did anything, but it was in my troubleshooting steps from a blog I found

pip install --upgrade pip setuptools wheel
sudo venv/bin/python3.11 -m pip install -r requirements.txt
sudo apt install -y libxml2-dev libxslt1-dev -y
sudo venv/bin/python3 pxethiefy.py -h
# Working!
```

**Comment by csandker** [comment]
Thanks for finding solutions to this problem. I think this problem came up with some scapy updates. To solve this I have now removed my previous version pinning for scapy and added an explicit import for `get_if_raw_hwaddr`. I think this should be solved now, but I haven't (and cannot) test all python/scapy version combinations.

If this issue persists with the updated code and scapy version, please reopen. 

Thanks again for contributing solutions and ideas <3

**Comment by 7MinSec** [comment]
Thanks much for all your work on this!  Tried it on a fresh pentest today and it worked like a champ (and found me goodies! :-)
